// Enriched Master Database with COD Cash Limits, SOS, Support Tickets & Growth Analytics
const PahadiMockDB = {
  towns: [
    {
      id: "solan",
      name: "Solan (Mushroom City)",
      center: [30.9084, 77.0999],
      zoom: 14,
      elevation: "1,502 m",
      activeRiders: 8,
      activeOrders: 14,
      weather: "clear",
      weatherSurgeFee: 0,
      weatherBufferMins: 0,
      todayGMV: 18450,
      todayOrders: 36,
      todayProfit: 2180,
      peakHourSurgeActive: false,
      zones: [
        {
          id: "solan-mall",
          name: "Mall Road & Kotwali",
          type: "commercial",
          coords: [[30.904, 77.095], [30.912, 77.097], [30.914, 77.104], [30.906, 77.103]],
          color: "#10b981",
          sla: "45-60 min"
        },
        {
          id: "solan-shamti",
          name: "Shamti Residential Corridor",
          type: "hill-slopes",
          coords: [[30.898, 77.101], [30.906, 77.104], [30.908, 77.112], [30.901, 77.110]],
          color: "#0ea5e9",
          sla: "60-75 min"
        }
      ]
    },
    {
      id: "dharamshala",
      name: "Dharamshala & McLeodGanj",
      center: [32.2190, 76.3234],
      zoom: 13,
      elevation: "1,457 m",
      activeRiders: 6,
      activeOrders: 11,
      weather: "rain",
      weatherSurgeFee: 15,
      weatherBufferMins: 20,
      todayGMV: 14200,
      todayOrders: 24,
      todayProfit: 1740,
      peakHourSurgeActive: true,
      zones: [
        {
          id: "dha-kotwali",
          name: "Lower Dharamshala (Kotwali)",
          type: "commercial",
          coords: [[32.212, 76.318], [32.222, 76.320], [32.225, 76.328], [32.215, 76.327]],
          color: "#10b981",
          sla: "45-60 min"
        },
        {
          id: "dha-mcleod",
          name: "McLeodGanj (Pedestrian Walking Zone)",
          type: "walking-runner",
          coords: [[32.235, 76.320], [32.246, 76.321], [32.248, 76.330], [32.237, 76.329]],
          color: "#a855f7",
          sla: "50-70 min"
        }
      ]
    },
    {
      id: "shimla",
      name: "Shimla (The Ridge)",
      center: [31.1048, 77.1734],
      zoom: 14,
      elevation: "2,276 m",
      activeRiders: 10,
      activeOrders: 21,
      weather: "clear",
      weatherSurgeFee: 0,
      weatherBufferMins: 0,
      todayGMV: 24600,
      todayOrders: 42,
      todayProfit: 3020,
      peakHourSurgeActive: false,
      zones: [
        {
          id: "shimla-ridge",
          name: "The Ridge / Mall Road (Zero Motor Vehicle Zone)",
          type: "walking-runner",
          coords: [[31.101, 77.168], [31.108, 77.170], [31.109, 77.179], [31.102, 77.177]],
          color: "#a855f7",
          sla: "45-65 min"
        },
        {
          id: "shimla-sanjauli",
          name: "Sanjauli Hill Belt",
          type: "steep-slopes",
          coords: [[31.102, 77.185], [31.112, 77.187], [31.115, 77.198], [31.104, 77.196]],
          color: "#f59e0b",
          sla: "65-90 min"
        }
      ]
    }
  ],

  merchants: [
    {
      id: "m1",
      name: "Anand Sweet Shop & Bakers",
      owner: "Ramesh Anand",
      town: "solan",
      category: "Bakery & Sweets",
      commissionRate: 14,
      address: "Mall Road, Near Old Bus Stand, Solan",
      phone: "+91 98160 12345",
      coords: [30.9092, 77.0988],
      status: "approved",
      vyaparMandalVerified: true,
      bankAccount: "HDFC Bank (A/C: ****4921, IFSC: HDFC000120)",
      todaySales: 6450,
      todayOrders: 16,
      pendingPayout: 5547,
      platformCutEarned: 903,
      strikeCount: 0,
      gstin: "02AAACA1234A1Z5"
    },
    {
      id: "m2",
      name: "Him Kirana & Organic Store",
      owner: "Surinder Thakur",
      town: "solan",
      category: "Grocery & Kirana",
      commissionRate: 6,
      address: "Shamti Bypass Chowk, Solan",
      phone: "+91 94180 54321",
      coords: [30.9021, 77.1054],
      status: "approved",
      vyaparMandalVerified: true,
      bankAccount: "State Bank of India (A/C: ****8812, IFSC: SBIN000067)",
      todaySales: 11200,
      todayOrders: 22,
      pendingPayout: 10528,
      platformCutEarned: 672,
      strikeCount: 1, // 1 rejection due to stock
      gstin: "02AABCT9876K1ZQ"
    },
    {
      id: "m3",
      name: "Pine View Cafe & Siddu Point",
      owner: "Devender Sharma",
      town: "solan",
      category: "Restaurant",
      commissionRate: 18,
      address: "Kotwali Bazaar, Solan",
      phone: "+91 98055 67890",
      coords: [30.9075, 77.1012],
      status: "approved",
      vyaparMandalVerified: true,
      bankAccount: "Punjab National Bank (A/C: ****3341, IFSC: PUNB0124)",
      todaySales: 4890,
      todayOrders: 11,
      pendingPayout: 4010,
      platformCutEarned: 880,
      strikeCount: 0,
      gstin: "02AALCP4432P1ZT"
    },
    {
      id: "m4",
      name: "Ridge Medicos (Emergency Pharmacy)",
      owner: "Dr. K.L. Gupta",
      town: "shimla",
      category: "Pharmacy",
      commissionRate: 5,
      address: "Near Gaiety Theatre, Mall Road, Shimla",
      phone: "+91 94181 99887",
      coords: [31.1045, 77.1725],
      status: "approved",
      vyaparMandalVerified: true,
      bankAccount: "ICICI Bank (A/C: ****7729, IFSC: ICIC000341)",
      todaySales: 8750,
      todayOrders: 19,
      pendingPayout: 8312,
      platformCutEarned: 438,
      strikeCount: 0,
      gstin: "02AABCR5511M1ZX"
    },
    {
      id: "m5",
      name: "Tibet Kitchen & Dumplings",
      owner: "Tenzin Norbu",
      town: "dharamshala",
      category: "Restaurant",
      commissionRate: 16,
      address: "Main Square, McLeodGanj",
      phone: "+91 98822 45678",
      coords: [32.2425, 76.3255],
      status: "approved",
      vyaparMandalVerified: true,
      bankAccount: "SBI McLeod Branch (A/C: ****1104, IFSC: SBIN000542)",
      todaySales: 9400,
      todayOrders: 18,
      pendingPayout: 7896,
      platformCutEarned: 1504,
      strikeCount: 0,
      gstin: "02AANCT3321N1ZL"
    }
  ],

  riders: [
    {
      id: "r1",
      name: "Aman Thakur",
      phone: "+91 98051 11223",
      vehicle: "Honda Activa 125 (Hill Tuned)",
      vehicleNumber: "HP-14-B-4421",
      town: "solan",
      coords: [30.9070, 77.1020],
      status: "in_transit",
      activeOrder: "PC-8921",
      todayDeliveries: 9,
      todayDistanceKm: 34.2,
      elevationClimbedMeters: 1420,
      earningsToday: 540,
      customerTips: 40,
      rating: 4.9,
      batteryPercent: 88,
      bankUPI: "amanthakur@okaxis",
      // COD Cash Defense Fields
      cashInHand: 2150,
      maxCashLimit: 2500,
      isCashLocked: false,
      thermalKitIssued: true,
      sosActive: false
    },
    {
      id: "r2",
      name: "Rohit Verma",
      phone: "+91 98166 44556",
      vehicle: "TVS Ntorq 125",
      vehicleNumber: "HP-14-C-8812",
      town: "solan",
      coords: [30.9035, 77.0980],
      status: "available",
      activeOrder: null,
      todayDeliveries: 7,
      todayDistanceKm: 26.5,
      elevationClimbedMeters: 980,
      earningsToday: 410,
      customerTips: 30,
      rating: 4.8,
      batteryPercent: 72,
      bankUPI: "rohitverma@paytm",
      cashInHand: 2780, // OVER THE LIMIT (Locked!)
      maxCashLimit: 2500,
      isCashLocked: true,
      thermalKitIssued: true,
      sosActive: false
    },
    {
      id: "r3",
      name: "Vikram Negi",
      phone: "+91 94182 88990",
      vehicle: "Walking Runner Partner (Mall Road)",
      vehicleNumber: "Pedestrian Pass #04",
      town: "shimla",
      coords: [31.1050, 77.1740],
      status: "in_transit",
      activeOrder: "PC-8919",
      todayDeliveries: 14,
      todayDistanceKm: 12.8,
      elevationClimbedMeters: 850,
      earningsToday: 680,
      customerTips: 70,
      rating: 5.0,
      batteryPercent: 95,
      bankUPI: "vikramnegi@oksbi",
      cashInHand: 1240,
      maxCashLimit: 2500,
      isCashLocked: false,
      thermalKitIssued: true,
      sosActive: false
    },
    {
      id: "r4",
      name: "Sonam Dorjee",
      phone: "+91 98820 99112",
      vehicle: "Walking Runner (McLeod)",
      vehicleNumber: "Pedestrian Pass #09",
      town: "dharamshala",
      coords: [32.2410, 76.3240],
      status: "available",
      activeOrder: null,
      todayDeliveries: 6,
      todayDistanceKm: 9.4,
      elevationClimbedMeters: 620,
      earningsToday: 360,
      customerTips: 20,
      rating: 4.7,
      batteryPercent: 64,
      bankUPI: "sonamdorjee@gpay",
      cashInHand: 850,
      maxCashLimit: 2500,
      isCashLocked: false,
      thermalKitIssued: false,
      sosActive: false
    },
    {
      id: "r5",
      name: "Rakesh Kashyap",
      phone: "+91 98162 77119",
      vehicle: "Hero Splendor Plus (Hill Gear)",
      vehicleNumber: "HP-14-A-1904",
      town: "solan",
      coords: [30.9010, 77.1060],
      status: "in_transit",
      activeOrder: "PC-8910",
      todayDeliveries: 4,
      todayDistanceKm: 16.0,
      elevationClimbedMeters: 510,
      earningsToday: 230,
      customerTips: 10,
      rating: 4.6,
      batteryPercent: 40,
      bankUPI: "rakeshkashyap@ybl",
      cashInHand: 420,
      maxCashLimit: 2500,
      isCashLocked: false,
      thermalKitIssued: true,
      sosActive: true // ACTIVE EMERGENCY SOS!
    }
  ],

  orders: [
    {
      id: "PC-8924",
      customerName: "Pooja Chandel",
      customerPhone: "+91 98164 55443",
      merchantId: "m1",
      merchantName: "Anand Sweet Shop & Bakers",
      town: "solan",
      items: [{ name: "Himachali Gulab Jamun (1kg)", qty: 1, price: 320 }, { name: "Fresh Pista Cookies Box", qty: 1, price: 160 }],
      amount: 480,
      merchantPayout: 412.80,
      platformCommission: 67.20,
      deliveryFee: 35,
      riderPayout: 45,
      platformFee: 5,
      gatewayFee: 8.64,
      netProfit: 48.56,
      total: 520,
      paymentMode: "UPI (Paid)",
      status: "placed",
      time: "2 mins ago",
      riderId: null,
      deliveryAddress: "Near Durga Club, Below Mall, Solan",
      staircaseNote: "Downward 15 stairs from roadside",
      eta: "45 mins",
      podPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80"
    },
    {
      id: "PC-8923",
      customerName: "Vikrant Chauhan",
      customerPhone: "+91 94180 11992",
      merchantId: "m3",
      merchantName: "Pine View Cafe & Siddu Point",
      town: "solan",
      items: [{ name: "Steamed Walnut Siddu (with Ghee)", qty: 2, price: 240 }, { name: "Kangra Masala Chai Flask", qty: 1, price: 120 }],
      amount: 360,
      merchantPayout: 295.20,
      platformCommission: 64.80,
      deliveryFee: 30,
      riderPayout: 42,
      platformFee: 5,
      gatewayFee: 0,
      netProfit: 57.80,
      total: 395,
      paymentMode: "COD (Cash on Delivery)",
      status: "preparing",
      time: "8 mins ago",
      riderId: "r2",
      deliveryAddress: "Shamti Colony, Gate No 2, Solan",
      staircaseNote: "Ground floor, road facing",
      eta: "50 mins",
      podPhoto: null
    },
    {
      id: "PC-8921",
      customerName: "Neeraj Rawat",
      customerPhone: "+91 98052 77881",
      merchantId: "m2",
      merchantName: "Him Kirana & Organic Store",
      town: "solan",
      items: [{ name: "Aashirvaad Sharbati Atta 5kg", qty: 1, price: 295 }, { name: "Pahadi Rajma (Red Kidney Beans 1kg)", qty: 1, price: 180 }, { name: "Amul Taaza Milk 1L", qty: 2, price: 136 }],
      amount: 611,
      merchantPayout: 574.34,
      platformCommission: 36.66,
      deliveryFee: 40,
      riderPayout: 52,
      platformFee: 5,
      gatewayFee: 11.00,
      netProfit: 18.66,
      total: 656,
      paymentMode: "UPI (Paid)",
      status: "in_transit",
      time: "22 mins ago",
      riderId: "r1",
      deliveryAddress: "Upper Kotwali, Opp. Tara Hall School",
      staircaseNote: "Upward 25 stairs on ridge",
      eta: "18 mins left",
      podPhoto: null
    },
    {
      id: "PC-8919",
      customerName: "Sanjay Sharma",
      customerPhone: "+91 98161 22334",
      merchantId: "m4",
      merchantName: "Ridge Medicos",
      town: "shimla",
      items: [{ name: "Pain Relief Balm & Vicks Inhaler", qty: 2, price: 190 }, { name: "Digital Thermometer", qty: 1, price: 260 }],
      amount: 450,
      merchantPayout: 427.50,
      platformCommission: 22.50,
      deliveryFee: 35,
      riderPayout: 45,
      platformFee: 5,
      gatewayFee: 8.10,
      netProfit: 9.40,
      total: 490,
      paymentMode: "UPI (Paid)",
      status: "in_transit",
      time: "31 mins ago",
      riderId: "r3",
      deliveryAddress: "Lakkar Bazaar, Footpath No 3, Shimla",
      staircaseNote: "Pedestrian Mall Walking Delivery",
      eta: "12 mins left",
      podPhoto: null
    },
    {
      id: "PC-8915",
      customerName: "Ananya Sen",
      customerPhone: "+91 98821 44332",
      merchantId: "m5",
      merchantName: "Tibet Kitchen & Dumplings",
      town: "dharamshala",
      items: [{ name: "Tibetan Veg Thukpa (Hot Bowl)", qty: 2, price: 320 }, { name: "Steamed Veg Momos (10 pcs)", qty: 2, price: 220 }],
      amount: 540,
      merchantPayout: 453.60,
      platformCommission: 86.40,
      deliveryFee: 50,
      riderPayout: 65,
      platformFee: 5,
      gatewayFee: 9.72,
      netProfit: 66.68,
      total: 595,
      paymentMode: "UPI (Paid)",
      status: "delivered",
      time: "54 mins ago",
      riderId: "r4",
      deliveryAddress: "Bhagsu Road, Homestay Solitude, McLeodGanj",
      staircaseNote: "Drop at homestay reception",
      eta: "Delivered (OTP: 7721)",
      podPhoto: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80"
    }
  ],

  // Customer Support & Tickets
  supportTickets: [
    {
      id: "TKT-104",
      customerName: "Kapil Chauhan",
      customerPhone: "+91 98165 99441",
      orderId: "PC-8912",
      issueType: "Damaged Items (Hill Curve Spill)",
      description: "Amul Milk pouch leaked during steep scooter climb near Shamti curve.",
      refundAmount: 68,
      status: "open", // open, refunded, closed
      createdTime: "12 mins ago"
    },
    {
      id: "TKT-103",
      customerName: "Sunita Verma",
      customerPhone: "+91 94182 33110",
      orderId: "PC-8908",
      issueType: "Late Delivery due to Rain",
      description: "Order arrived 35 mins late due to fog. Requesting compensation voucher.",
      refundAmount: 50,
      status: "open",
      createdTime: "40 mins ago"
    },
    {
      id: "TKT-101",
      customerName: "Rajesh Sood",
      customerPhone: "+91 98055 22119",
      orderId: "PC-8899",
      issueType: "Wrong Sweet Box Delivered",
      description: "Ordered Kaju Katli, received Gulab Jamun. Issue verified by merchant.",
      refundAmount: 240,
      status: "refunded",
      createdTime: "2 hours ago"
    }
  ],

  // Growth & Colony Heatmap Intelligence
  colonyHeatmap: [
    { colony: "Shamti Residential Bypass (Solan)", totalOrders: 142, repeatRate: "68%", growthTrend: "+24%", avgEta: "52m" },
    { colony: "Mall Road & Kotwali (Solan)", totalOrders: 188, repeatRate: "76%", growthTrend: "+18%", avgEta: "38m" },
    { colony: "Kumarhatti University Corridor", totalOrders: 96, repeatRate: "54%", growthTrend: "+35%", avgEta: "58m" },
    { colony: "The Ridge & Sanjauli (Shimla)", totalOrders: 215, repeatRate: "81%", growthTrend: "+19%", avgEta: "44m" },
    { colony: "McLeodGanj Homestay Belt", totalOrders: 112, repeatRate: "42%", growthTrend: "+41%", avgEta: "48m" }
  ],

  // Marketing Coupons Burn vs ROI
  coupons: [
    { code: "PEHLA", discount: "Free Delivery (₹35)", totalRedeemed: 420, burnAmount: 14700, gmvGenerated: 196000, roiMultiple: "13.3x" },
    { code: "PAHADICHA", discount: "₹30 Off on Siddu/Chai", totalRedeemed: 210, burnAmount: 6300, gmvGenerated: 78500, roiMultiple: "12.4x" },
    { code: "RAIN50", discount: "₹50 Off in Rain/Fog", totalRedeemed: 95, burnAmount: 4750, gmvGenerated: 54200, roiMultiple: "11.4x" }
  ],

  // Inactive Customers for WhatsApp Re-engagement
  inactiveCustomers: [
    { name: "Meenakshi Sharma", phone: "+91 98160 88219", town: "Solan", lastOrderDays: 19, totalSpent: 2150 },
    { name: "Amit Thakur", phone: "+91 94181 44521", town: "Solan", lastOrderDays: 24, totalSpent: 1890 },
    { name: "Gaurav Negi", phone: "+91 98051 77332", town: "Shimla", lastOrderDays: 28, totalSpent: 3400 },
    { name: "Tsering Dolma", phone: "+91 98822 11990", town: "Dharamshala", lastOrderDays: 31, totalSpent: 1650 }
  ],

  financialSummary: {
    monthToDateGMV: 184250,
    merchantPayoutsProcessed: 156400,
    merchantDuesPending: 18240,
    riderPayoutsProcessed: 14850,
    gatewayAndSmsFees: 2950,
    netFounderProfitMtd: 21850,
    netProfitMarginPct: 11.8,
    averageOrderValue: 468,
    totalCompletedOrdersMonth: 394
  },

  categoryShare: [
    { name: "Grocery & Kirana", percent: 41, gmv: 75542, avgComm: "6.2%" },
    { name: "Bakery & Sweets", percent: 24, gmv: 44220, avgComm: "14.0%" },
    { name: "Cafes & Restaurants", percent: 23, gmv: 42377, avgComm: "17.4%" },
    { name: "Pharmacy & Emergency", percent: 12, gmv: 22111, avgComm: "5.0%" }
  ]
};
